# Creating a logistic regression to predict absenteeism

###### Import the libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('/Users/kapilakhaded/Documents/Study/Integration SQL Python Tableau/5. Preprocessing/What to Expect from the Next Couple of Sections/Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Date of the Week  \
0         0         0         0         1             7                 1   
1         0         0         0         0             7                 1   
2         0         0         0         0             7                 2   
3         1         0         0         0             7                 3   
4         0         0         0         0             7                 3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  Date of the Week  \
0         0         0         0         1             7                 1   
1         0         0         0         0             7                 1   
2         0         0         0         0             7                 2   
3         1         0         0         0             7                 3   
4         0         0         0         0             7                 3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [9]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Date of the Week', 'Distance to Work', 'Daily Work Load Average'],axis=1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  \
0         0         0         0         1             7   
1         0         0         0         0             7   
2         0         0         0         0             7   
3         1         0         0         0             7   
4         0         0         0         0             7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [13]:
#Select all except last column
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  \
0           0         0         0         1             7   
1           0         0         0         0             7   
2           0         0         0         0             7   
3           1         0         0         0             7   
4           0         0         0         0             7   
..        ...       ...       ...       ...           ...   
695         1         0         0         0             5   
696         1         0         0         0             5   
697         1         0         0         0             5   
698         0         0         0         0             5   
699         0         0         0         1             5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [14]:
#Same result can be achoeved with below
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  \
0           0         0         0         1             7   
1           0         0         0         0             7   
2           0         0         0         0             7   
3           1         0         0         0             7   
4           0         0         0         0             7   
..        ...       ...       ...       ...           ...   
695         1         0         0         0             5   
696         1         0         0         0             5   
697         1         0         0         0             5   
698         0         0         0         0             5   
699         0         0         0         1             5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [15]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

#### Standardize the data

In [16]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [17]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [18]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Values',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [19]:
#columns_to_scale = ['Month Values',
#       'Date of the Week', 'Transportation Expense', 'Distance to Work',
#       'Age', 'Daily Work Load Average', 'Body Mass Index',
#       'Children', 'Pets']
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [20]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [21]:
absenteeism_scaler=CustomScaler(columns_to_scale)

In [22]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Values', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'],
             copy=None, with_mean=None, with_std=None)

In [23]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [24]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Values  \
0           0         0         0         1      0.182726   
1           0         0         0         0      0.182726   
2           0         0         0         0      0.182726   
3           1         0         0         0      0.182726   
4           0         0         0         0      0.182726   
..        ...       ...       ...       ...           ...   
695         1         0         0         0     -0.388293   
696         1         0         0         0     -0.388293   
697         1         0         0         0     -0.388293   
698         0         0         0         0     -0.388293   
699         0         0         0         1     -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [25]:
scaled_inputs.shape

(700, 11)

### Split the data into train and test data sets and shuffle

##### Import the relevant module

In [26]:
from sklearn.model_selection import train_test_split

#### Split the data

In [27]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Values  \
 184         0         0         0         1     -0.673803   
 291         0         0         0         1      1.039256   
 618         0         0         0         1     -0.959313   
 183         0         0         0         1     -0.959313   
 632         0         0         0         1     -0.959313   
 ..        ...       ...       ...       ...           ...   
 497         0         0         0         1      0.753746   
 504         0         0         0         0      0.753746   
 456         0         0         1         0     -0.102784   
 113         0         0         0         0     -1.530333   
 670         0         0         0         1     -0.673803   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 184                1.036026  0.562059        -0.408580          0 -0.019280   
 291                1.005844 -0.536062         0.767431          0  0.880469   
 618          

In [28]:
#Set train_size to 0.8 to split the dataset into 80% train and 20% test 
# To avoid random shuffle everytime, set the rand_shuffle parameter to number(say 20) to make shuffle pseudo random and to shuffle the observation in the same 'random' way  
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state =20)

In [29]:
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [30]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


### Logistic Regression with SKLearn

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [32]:
reg = LogisticRegression()

In [33]:
reg.fit(x_train,y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
reg.score(x_train,y_train)

0.7446428571428572

#### Manually check the accuracy

In [35]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [36]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [37]:
model_output == y_train

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False,  True, False,  True,  True,  True,
        True,  True,

In [38]:
np.sum(model_output == y_train)

417

In [39]:
np.sum(model_output == y_train) / model_output.shape[0]

0.7446428571428572

#### Finding the intercepts and coefficients  

In [40]:
reg.intercept_

array([-0.78909506])

In [41]:
reg.coef_

array([[ 1.73232539, -0.02914068,  2.49851518, -0.05197078,  0.18998131,
         0.51246437, -0.07505299,  0.17993425, -0.02719511,  0.28630753,
        -0.34490098]])

In [42]:
#Below error is due to standardization performed on pandas dataframe using sklearn (StandardScalar) which stores the output as ndarray and prevents any further sklearn functions
#sklearn methods are compateable with pandas dataframe but when performed sklearn function everything is transformed to ndarray
scaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Values',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [43]:
#use unscaled_input DF to find the column names
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Values',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [44]:
feature_name = unscaled_inputs.columns.values

In [45]:
#Assign feature name as first column
summary_table = pd.DataFrame(data = feature_name, columns=['Feature name'])
#Assign coefficient as next column. Note as coefficient are displayed as array (or row) it needs to be transposed to columns 
summary_table['Coeeficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coeeficient
0                 Reason_1     1.732325
1                 Reason_2    -0.029141
2                 Reason_3     2.498515
3                 Reason_4    -0.051971
4             Month Values     0.189981
5   Transportation Expense     0.512464
6                      Age    -0.075053
7          Body Mass Index     0.179934
8                Education    -0.027195
9                 Children     0.286308
10                    Pets    -0.344901

##### Add intercept to the start of the dataframe
1. Shift indexes
2. add intercept row (with name as 'Intercept' and value as first value in intercept array) to start of the dataframe
3. sort the dataframe using index

In [46]:
summary_table.index = summary_table.index +1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()

In [47]:
summary_table

Feature name  Coeeficient
0                Intercept    -0.789095
1                 Reason_1     1.732325
2                 Reason_2    -0.029141
3                 Reason_3     2.498515
4                 Reason_4    -0.051971
5             Month Values     0.189981
6   Transportation Expense     0.512464
7                      Age    -0.075053
8          Body Mass Index     0.179934
9                Education    -0.027195
10                Children     0.286308
11                    Pets    -0.344901

### interpreting the coefficients

In [48]:
summary_table['Odd_ratio'] = np.exp(summary_table['Coeeficient'])

In [49]:
summary_table

Feature name  Coeeficient  Odd_ratio
0                Intercept    -0.789095   0.454256
1                 Reason_1     1.732325   5.653786
2                 Reason_2    -0.029141   0.971280
3                 Reason_3     2.498515  12.164419
4                 Reason_4    -0.051971   0.949357
5             Month Values     0.189981   1.209227
6   Transportation Expense     0.512464   1.669400
7                      Age    -0.075053   0.927694
8          Body Mass Index     0.179934   1.197139
9                Education    -0.027195   0.973171
10                Children     0.286308   1.331502
11                    Pets    -0.344901   0.708290

In [50]:
summary_table.sort_values('Odd_ratio',ascending = False)
# If coefficient is around 0 or oddratio is around 1 then feature is not particulrly important
# With this logic features with nos Daily Work Load Avg, Distance to Work, Date of the week may not relevant

Feature name  Coeeficient  Odd_ratio
3                 Reason_3     2.498515  12.164419
1                 Reason_1     1.732325   5.653786
6   Transportation Expense     0.512464   1.669400
10                Children     0.286308   1.331502
5             Month Values     0.189981   1.209227
8          Body Mass Index     0.179934   1.197139
9                Education    -0.027195   0.973171
2                 Reason_2    -0.029141   0.971280
4                 Reason_4    -0.051971   0.949357
7                      Age    -0.075053   0.927694
11                    Pets    -0.344901   0.708290
0                Intercept    -0.789095   0.454256

Now go back to standardization section to exclude the dummy variables from standardization and re-run all code till this point.
Also perform backword elimination to simply model by removing features which dont contribute to the model. We can elimate Distance to work and education 

## Testing the model

In [51]:
reg.score(x_test,y_test)

0.7214285714285714

In [52]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.69478348, 0.30521652],
       [0.59405756, 0.40594244],
       [0.47365469, 0.52634531],
       [0.77842495, 0.22157505],
       [0.41235476, 0.58764524],
       [0.37103366, 0.62896634],
       [0.36580214, 0.63419786],
       [0.11533098, 0.88466902],
       [0.8208516 , 0.1791484 ],
       [0.72860852, 0.27139148],
       [0.11414976, 0.88585024],
       [0.03171039, 0.96828961],
       [0.06356424, 0.93643576],
       [0.16958004, 0.83041996],
       [0.75292211, 0.24707789],
       [0.54931266, 0.45068734],
       [0.67275813, 0.32724187],
       [0.13799181, 0.86200819],
       [0.37529102, 0.62470898],
       [0.05372749, 0.94627251],
       [0.71661687, 0.28338313],
       [0.77842495, 0.22157505],
       [0.40738521, 0.59261479],
       [0.40738521, 0.59261479],
       [0.23306534, 0.76693466],
       [0.77745909, 0.22254091],
       [0.50175878, 0.49824122],
       [0.78917276, 0.21082724],
       [0.15085547, 0.84914453],
       [0.77842495, 0.22157505],
       [0.

In [53]:
predicted_proba.shape

(140, 2)

In [54]:
predicted_proba[:,1]

array([0.30521652, 0.40594244, 0.52634531, 0.22157505, 0.58764524,
       0.62896634, 0.63419786, 0.88466902, 0.1791484 , 0.27139148,
       0.88585024, 0.96828961, 0.93643576, 0.83041996, 0.24707789,
       0.45068734, 0.32724187, 0.86200819, 0.62470898, 0.94627251,
       0.28338313, 0.22157505, 0.59261479, 0.59261479, 0.76693466,
       0.22254091, 0.49824122, 0.21082724, 0.84914453, 0.22157505,
       0.87574673, 0.59161638, 0.65390936, 0.89636938, 0.22157505,
       0.911023  , 0.1872641 , 0.23321473, 0.37447214, 0.58764524,
       0.21236091, 0.49461189, 0.20433732, 0.58764524, 0.777002  ,
       0.1428923 , 0.65713694, 0.31634759, 0.24745048, 0.20342979,
       0.63994001, 0.55817722, 0.62896634, 0.31285468, 0.80274366,
       0.44514396, 0.84859033, 0.23362105, 0.51223921, 0.52577916,
       0.70242375, 0.61622209, 0.3194469 , 0.2618791 , 0.18949963,
       0.29336615, 0.2192727 , 0.1953027 , 0.80818035, 0.85882594,
       0.1872641 , 0.52066558, 0.87479275, 0.45266717, 0.52526

## Save the model

Save model using python module pickle which converts python object into character stream. In this exercise its saving Reg object

In [55]:
import pickle

In [58]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [59]:
with open('absenteeism_scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)